config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :items
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  acts_as_tenant(:user)
  belongs_to :user
  has_one_attached :mockup
  has_rich_text :background
  has_rich_text :objective
  has_rich_text :assumptions
  has_rich_text :success
  has_rich_text :user_stories
  has_rich_text :use_cases
  has_rich_text :requirements
  has_rich_text :milestones
  has_rich_text :questions
  has_rich_text :scope
  has_rich_text :why
  has_rich_text :supporting_data
  has_rich_text :inspiration
  has_rich_text :dependencies
  has_rich_text :risks
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(user_id: current_user.id)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@item.name}_prd"   # Excluding ".pdf" extension.
      end
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.mockup.attach(params[:mockup])
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update

    @item.mockup.attach(params[:mockup])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:user_id, :name, :description, :release_date, :epic, :status, :owner, :designer, :developer, :tech_lead, :qa, :background, :objective, :assumptions, :success, :user_stories, :use_cases, :requirements, :milestones, :questions, :scope, :why, :supporting_data, :inspiration, :dependencies, :risks, :mockup)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>



  <div class="form-group">
    <%= form.label "Mockup" %>
    <%= form.file_field :mockup %>
  </div>


  <div class="form-group">
    <%= form.label :release_date %>
    <%= form.datetime_select :release_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :epic %>
    <%= form.text_field :epic, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :owner %>
    <%= form.text_field :owner, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :designer %>
    <%= form.text_field :designer, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :developer %>
    <%= form.text_field :developer, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tech_lead %>
    <%= form.text_field :tech_lead, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :qa %>
    <%= form.text_field :qa, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :background %>
    <%= form.rich_text_area :background, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :objective %>
    <%= form.rich_text_area :objective, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :assumptions %>
    <%= form.rich_text_area :assumptions, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :success %>
    <%= form.rich_text_area :success, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :user_stories %>
    <%= form.rich_text_area :user_stories, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :use_cases %>
    <%= form.rich_text_area :use_cases, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :requirements %>
    <%= form.rich_text_area :requirements, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :milestones %>
    <%= form.rich_text_area :milestones, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :questions %>
    <%= form.rich_text_area :questions, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :scope %>
    <%= form.rich_text_area :scope, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :why %>
    <%= form.rich_text_area :why, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :supporting_data %>
    <%= form.rich_text_area :supporting_data, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :inspiration %>
    <%= form.rich_text_area :inspiration, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :dependencies %>
    <%= form.rich_text_area :dependencies, class: 'form-control bigger-form' %>
  </div>

  <div class="form-group">
    <%= form.label :risks %>
    <%= form.rich_text_area :risks, class: 'form-control bigger-form' %>
  </div>

  <%= form.hidden_field(:user_id, :value => current_user.id) %>

  <div class="form-group">
    <% if item.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', item, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary p-20' %>

    <% if item.persisted? %>
      <%= link_to "Cancel", item, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", items_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>


<style>
.bigger-form {
  height: 100px;
  resize: height:
}
</style>

app/views/items/edit.html.erb
<h1>Edit Spec</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>My Specs</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    Add New Item
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Description</th>
            <th>Release Date</th>
            <th>Epic</th>
            <th>Status</th>
            <th>Owner</th>
            <th>PDF</th>
            
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <%= content_tag :tr, id: dom_id(item), class: dom_class(item) do %>
          <td><%= link_to item.name, item %></td>
          <td><%= item.description %></td>
          <td><%= item.release_date %></td>
          <td><%= item.epic %></td>
          <td><%= item.status %></td>
          <td><%= item.owner %></td>         
          <td> 
            <%= link_to item_path(item, format: :pdf), class: "btn btn-secondary", title: "Download PDF Version" do %>
              <i class="far fa-file-pdf"></i> Download PDF
            <% end %>
          </td>          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    All Items
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <%= link_to item_path(@item, format: :pdf), class: "btn btn-secondary", title: "Download PDF Version" do %>
    <i class="far fa-file-pdf"></i> Download PDF
  <% end %>
  <h1><%= @item.name %></h1>
  <h3><%= @item.description %></h3>
</div>

  <dt>Key Info:</dt>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Release Date</th>
            <th>Epic</th>
            <th>Status</th
      </tr>
    </thead>

    <tbody>
      <td><%= @item.release_date %></td>
      <td><%= @item.epic %></td>
      <td><%= @item.status %></td>
    </tbody>
  </table>
</div>

<dt>Responsible Parties:</dt>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Owner</th>
            <th>Designer</th>
            <th>Developer</th>
            <th>Tech Lead</th>
            <th>QA</th>
      </tr>
    </thead>

    <tbody>
      <td><%= @item.owner %></td>
      <td><%= @item.designer %></td>
      <td><%= @item.developer %></td>
      <td><%= @item.tech_lead %></td>
      <td><%= @item.qa %></td>
    </tbody>
  </table>
</div>

  <dt>Mockup:</dt>
  <% if @item.mockup.attached? %>
    <dd><%= image_tag @item.mockup, style:"max-width: 200px" %></dd>
    <%= link_to "view mockup", url_for(@item.mockup) %>
  <% else %>
    <dd>No mockup attached</dd>
  <% end %>

  <dt>Background:</dt>
  <dd><%= @item.background %></dd>

  <dt>Objective:</dt>
  <dd><%= @item.objective %></dd>

  <dt>Assumptions:</dt>
  <dd><%= @item.assumptions %></dd>

  <dt>Success:</dt>
  <dd><%= @item.success %></dd>

  <dt>User stories:</dt>
  <dd><%= @item.user_stories %></dd>

  <dt>Use cases:</dt>
  <dd><%= @item.use_cases %></dd>

  <dt>Requirements:</dt>
  <dd><%= @item.requirements %></dd>

  <dt>Milestones:</dt>
  <dd><%= @item.milestones %></dd>
  
  <dt>Questions:</dt>
  <dd><%= @item.questions %></dd>

  <dt>Scope:</dt>
  <dd><%= @item.scope %></dd>

  <dt>Supporting data:</dt>
  <dd><%= @item.supporting_data %></dd>

  <dt>Inspiration:</dt>
  <dd><%= @item.inspiration %></dd>

  <dt>Dependencies:</dt>
  <dd><%= @item.dependencies %></dd>

  <dt>Risks:</dt>
  <dd><%= @item.risks %></dd>

</dl>

app/views/items/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/97c093f09e.js" crossorigin="anonymous"></script>

    <style>

        .flex-container {
            -webkit-display: -webkit-box;
            -webkit-display: -webkit-flex;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            flex-direction: column;
            -webkit-flex-wrap: wrap;
            
        }
        .flex-item {
            /* **display: inline-block;** (To wrap on new line) */
            margin: 5px;
            font-size: 17px;
            text-align: left;
        }

    </style>
  </head>
  <body class="m-8">

      <div class="my-6">
        <h3 class="text-xl uppercase leading-6 font-bold text-gray-900"><%= @item.name %></h3>
        <p class="mt-1 text-sm leading-5 text-gray-500"><%= @item.description %></p>
      </div>

      <div class="align-middle inline-block shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
        <table class="min-w-full">
          <thead>
            <tr>
                  <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Release Date</th>
                  <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Epic</th>
                  <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</th
            </tr>
          </thead>

          <tbody>
            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.release_date %></td>
            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.epic %></td>
            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.status %></td>
          </tbody>
        </table>
      </div>
      <div class="align-middle inline-block shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
        <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Responsible Parties:</dt>
        <div class="table-responsive">
          <table class="min-w-full">
            <thead>
              <tr>
                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Owner</th>
                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Designer</th>
                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Developer</th>
                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Tech Lead</th>
                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">QA</th>
              </tr>
            </thead>

            <tbody>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.owner %></td>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.designer %></td>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.developer %></td>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.tech_lead %></td>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= @item.qa %></td>
            </tbody>
          </table>
        </div>
      </div>
      <div class="flex-item">
        <dl>
          <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Mockup:</dt>
          <% if @item.mockup.attached? %>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= link_to "view mockup", url_for(@item.mockup) %></dd>
          <% else %>
            <dd class="mt-1 text-sm leading-5 text-gray-900">No mockup attached</dd>
          <% end %>
        
          <% unless @item.background.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Background:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.background %></dd>
          <% end %>
          <% unless @item.objective.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Objective:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.objective %></dd>
          <% end %>
          <% unless @item.assumptions.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Assumptions:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.assumptions %></dd>
          <% end %>
          <% unless @item.success.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Success:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.success %></dd>
          <% end %>
          <% unless @item.user_stories.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">User stories:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.user_stories %></dd>
          <% end %>
          <% unless @item.use_cases.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Use cases:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.use_cases %></dd>
          <% end %>
          <% unless @item.requirements.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Requirements:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.requirements %></dd>
          <% end %>
          <% unless @item.milestones.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Milestones:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.milestones %></dd>
          <% end %>
          <% unless @item.questions.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Questions:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.questions %></dd>
          <% end %>
          <% unless @item.scope.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Scope:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.scope %></dd>
          <% end %>
          <% unless @item.supporting_data.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Supporting data:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.supporting_data %></dd>
          <% end %>
          <% unless @item.inspiration.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Inspiration:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.inspiration %></dd>
          <% end %>
          <% unless @item.dependencies.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Dependencies:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.dependencies %></dd>
          <% end %>
          <% unless @item.risks.blank? %>
            <dt class="uppercase text-sm leading-5 font-bold text-gray-500 pt-4 pb-2">Risks:</dt>
            <dd class="mt-1 text-sm leading-5 text-gray-900"><%= @item.risks %></dd>
          <% end %>
        </dl>
      </div>
  </body>
</html>